---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
  hosts: wordpress-server
  user: root
  # remote_user: user
  # sudo: yes

  roles:
    # - common
    - wordpress
    # - mysql 
    # - nginx
    - php-fpm
